### ISSUE TITLE
BlueBuild

### ISSUE THREAD

**Issue by Malix-Labs** [playtron-os/playtron-os#150]
Since PlaytronOS is based on Fedora Atomic, wouldn't it be a good idea to rebase it on [Blue Build](https://blue-build.org/) instead _(Like [Universal Blue](https://universal-blue.org/))_ ?

**Comment by LukeShortCloud** [comment]
Thanks for the suggestion @Malix-Labs !

What are the advantages of using the Blue Build system? We're currently using OSTree files for building our base image and then a Containerfile for building the final image. This aligns with Red Hat's current recommendations for Atomic Desktop builds.

**Comment by Malix-Labs** [comment]
The main benefits is that most of the work has already been done, but it's still possible to make deep edits after that, see:

> "Why build an abstraction on top of Containerfiles? (recipe.yml)"
 https://blue-build.org/#:~:text=Why%20build%20an%20abstraction%20on%20top%20of%20Containerfiles%3F%20(recipe.yml)

**Comment by alkazar** [comment]
We have already discussed this internally. The issue is that we plan to ship to consumer devices and ublue changes too frequently which can lead to instability.

For our case we need to be in control of the packages we deliver to our users and update at a rate that is sustainable by our own QA team. In other words, we are focused on stability, ublue is focused on the bleeding edge.

**Comment by Malix-Labs** [comment]
Then what about just VIB ?
